DROP TABLE IF EXISTS users_events CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS opening_hours CASCADE;

DROP TABLE IF EXISTS sport_complexes CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS address CASCADE;

-- ALTER SEQUENCE address_id_seq RESTART WITH 1;
-- ALTER SEQUENCE sport_complexes_id_seq RESTART WITH 1;
-- ALTER SEQUENCE opening_hours_id_seq RESTART WITH 1;
-- ALTER SEQUENCE users_id_seq RESTART WITH 1;
-- ALTER SEQUENCE events_id_seq RESTART WITH 1;
-- ALTER SEQUENCE users_events_id_seq RESTART WITH 1;
-- ALTER SEQUENCE reviews_id_seq RESTART WITH 1;